# Generated by Django 6.0.5 on 2026-06-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_id',
        ),
    ]
