# Generated by Django 6.0.5 on 2026-06-04 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_api', '0002_remove_word_word_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word'], 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AlterField(
            model_name='word',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=46, unique=True),
        ),
    ]
